bcgov/nr-nmp

- frontend/src/main.tsx
> Test to see if deploys to OpenShift

- .github/workflows/.deploy.yml
- .github/workflows/pr-open.yml
- frontend/openshift.deploy.yml
---
- [Frontend](https://nr-nmp-32-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-32-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
> chore(ci): update security context

- .github/workflows/.deploy.yml
- .github/workflows/pr-open.yml
- backend/openshift.deploy.yml
- common/openshift.init.yml
- database/openshift.deploy.yml
---
- [Frontend](https://nr-nmp-36-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-36-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
> chore(ci): frontend init deploy

- docker-compose.yml
- frontend/Caddyfile
- frontend/Dockerfile
- frontend/openshift.deploy.yml
---
- [Frontend](https://nr-nmp-37-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-37-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
> chore(ci): Caddy Setup

- .github/workflows/.deploy.yml
---
- [Frontend](https://nr-nmp-44-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-44-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
> chore(ci): Updated github variables

- .github/workflows/.deploy.yml
---
- [Frontend](https://nr-nmp-50-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-50-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
> chore(ci): Updated suffix name

- .github/workflows/.deploy.yml
---
- [Frontend](https://nr-nmp-51-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-51-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
> chore(ci): renamed nameSuffix

- .github/workflows/merge.yml
---
- [Frontend](https://nr-nmp-52-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-52-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
> chore(ci): added test comment

- .github/workflows/merge.yml
- .github/workflows/pr-close.yml
---
- [Frontend](https://nr-nmp-53-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-53-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
> chore(ci): remove Comment to test deploy

- .github/workflows/.deploy.yml
- .github/workflows/merge.yml
- .github/workflows/pr-close.yml
---
- [Frontend](https://nr-nmp-56-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-56-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
> chore(ci): Test deploy 4

- .github/workflows/merge.yml
---
- [Frontend](https://nr-nmp-59-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-59-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
> chore(ci): Deploy prod

- backend/Dockerfile
- frontend/Dockerfile
- frontend/openshift.deploy.yml
---
- [Frontend](https://nr-nmp-60-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-60-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
> chore(ci): Uncommented readiness probe

- frontend/openshift.deploy.yml
---
- [Frontend](https://nr-nmp-94-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-94-frontend.apps.silver.devops.gov.bc.ca/api)
> feat: This is a test (Updated frontend deploy)

- frontend/openshift.deploy.yml
---
- [Frontend](https://nr-nmp-95-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-95-frontend.apps.silver.devops.gov.bc.ca/api)
> feat: This is a test (Updated frontend deploy) #94

- .github/workflows/.deploy.yml
- frontend/openshift.deploy.yml
---
- [Frontend](https://nr-nmp-96-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-96-frontend.apps.silver.devops.gov.bc.ca/api)
> feat: Environmnet test

- frontend/src/routes/ViewRouter.tsx
- frontend/src/views/AdminDashboard/AdminDashboard.tsx
- Added page with simple div
- Page is routed to at /admin
---
- [Frontend](https://nr-nmp-101-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-101-frontend.apps.silver.devops.gov.bc.ca/api)
> feat: [NMP-86] Added base page at /admin

- database/db/seed_tables/_Crops/init_crops.sql
- docker-compose.yml
- frontend/openshift.deploy.yml
- frontend/src/utils/APICache.ts
---
- [Frontend](https://nr-nmp-174.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-174-backend.apps.silver.devops.gov.bc.ca/healthcheck/)
> fix: Removed code causing docker compose up database to fail

- .github/workflows/.deploy.yml
---
- [Frontend](https://nr-nmp-189.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-189-backend.apps.silver.devops.gov.bc.ca/healthcheck/)
> fix: Set deploys to overwrite

- frontend/src/main.tsx
- frontend/src/views/AnimalsAndManure/AddAnimals/AddAnimals.tsx
- Removed StrictMode which caused handleAdd appends to run twice
---
- [Frontend](https://nr-nmp-200.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-200-backend.apps.silver.devops.gov.bc.ca/healthcheck/)
> fix: [NR-NMP-194] Removed StrictMode

- backend/Dockerfile
---
- [Frontend](https://nr-nmp-218.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-218-backend.apps.silver.devops.gov.bc.ca/healthcheck/)
> feat: [NP-NMP-199] Edit Migrate

- Makefile
- backend/apps/animals/tests/test_models.py
- backend/apps/crops/tests/test_models.py
- backend/apps/fertilizers/tests/test_models.py
- backend/apps/manures/tests/test_models.py
- Added tests for models in backend
- Tests can be added and dropped to whatever devs deem necessary, this is a starting point based on what is available now
- Added makefile to run tests locally with easier to digest commands
- In an upcoming ticket, will add linting and automatic testing when opening a PR 
---
- [Frontend](https://nr-nmp-227.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-227-backend.apps.silver.devops.gov.bc.ca/healthcheck/)
- [Merge …
> feat: [NR-NMP-198] Django Model Tests

- .github/workflows/.tests.yml
- .github/workflows/merge.yml
- .github/workflows/pr-open.yml
- frontend/.eslintrc.cjs
- frontend/babel.config.cjs
- frontend/jest.config.cjs
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/common/AppTitle/AppTitle.test.tsx
- frontend/tsconfig.json
---
- [Frontend](https://nr-nmp-253.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-253-backend.apps.silver.devops.gov.bc.ca/healthcheck/)
> ci: [NR-NMP-203] Add Jest to PR checks

- frontend/package-lock.json
- frontend/package.json
- frontend/src/common.styles.ts
- frontend/src/views/FarmInformation/FarmInformation.tsx
- frontend/src/views/FieldList/FieldList.tsx
- frontend/src/views/FieldList/fieldList.styles.ts
- frontend/src/views/SoilTests/SoilTests.tsx
- frontend/src/views/SoilTests/soilTests.styles.ts
- Changes to Soil test page
- Added common title/progress bar/other styling components
- Added new Soil Test table
- Added new Soil Test entry modal
- Updated view specific styling
- Updated common stylings
---
- [Frontend](https://nr-nmp-254.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-254-backend.apps.silver.devops.gov.bc.ca/healthcheck/)
---
Deployments, as required, will be …
> feat: [NR-NMP-236] Soil Test table for Field Information page

- .github/workflows/.tests.yml
- frontend/.eslintrc.cjs
- frontend/README.md
- frontend/cypress.config.ts
- frontend/cypress.d.ts
- frontend/cypress/README.md
- frontend/cypress/support/component-index.html
- frontend/cypress/support/component.ts
- frontend/package-lock.json
- frontend/package.json
- frontend/src/views/FarmInformation/FarmInformation.cy.tsx
- frontend/src/views/FarmInformation/FarmInformation.tsx
- frontend/tsconfig.cy.json
- Added Cypress to frontend with basic config
- Split out the `npm run test` command to be able to run Jest, Cypress, or both
- Started README of common Cypress bugs
- Updated general README
---
- [Frontend](https://nr-nmp-267.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-267-backend.apps.silver.devops.gov.bc.ca/healthcheck/)
> ci: [NR-NMP-204] Add Cypress to tests

- frontend/cypress/support/component.ts
- frontend/tsconfig.json
- Removed the duplicate declaration pointed out by Conor
---
- [Frontend](https://nr-nmp-269.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-269-backend.apps.silver.devops.gov.bc.ca/healthcheck/)
---
- [Frontend](https://nr-nmp-269.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-269-backend.apps.silver.devops.gov.bc.ca/heal …
> ci: Add commented out instructions for Cypress

- frontend/src/views/NutrientAnalysis/NutrientAnalysis.tsx
- frontend/src/views/NutrientAnalysis/NutrientAnalysisModal.tsx
- frontend/src/views/NutrientAnalysis/nutrientAnalsysis.styles.ts
- Implement new styling changes
- Implement new modal and form inputs
- Adjust nutrient calculations
- Display calculations in new table
---
- [Frontend](https://nr-nmp-302.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-302-backend.apps.silver.devops.gov.bc.ca/healthcheck/)
> feat: [NR-NMP-266] Nutrient Analysis UI rework

- frontend/src/views/CalculateNutrients/CalculateNutrients.tsx
- frontend/src/views/CalculateNutrients/FertilizerModal/NewFertilizerModal.tsx
- frontend/src/views/CalculateNutrients/types.ts
- Created new modal 'Add Fertilizer' for Calculate nutrients page
- Added error handling to prevent page from crashing if no fields are entered.
---
- [Frontend](https://nr-nmp-308.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-308-backend.apps.silver.devops.gov.bc.ca/healthcheck/)
> feat: [NR-NMP-131] Add refactored 'Add Fertilizer' modal to Calculate Nutrients page

- frontend/src/constants/routes.ts
- frontend/src/views/Reporting/Reporting.tsx
Fixing the route value for landing page so the router can navigate to it.
Correct the nmp file extension for generate nmp file.
- Route constant value for LANDING_PAGE changed to '/'
- Extension for NMP file to .nmp
---
- [Frontend](https://nr-nmp-328.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-328-backend.apps.silver.devops.gov.bc.ca/healthcheck/)
> fix: Fix back button to landing page, update nmp file extension

- frontend/src/views/NutrientAnalysis/NutrientAnalysis.tsx
- frontend/src/views/NutrientAnalysis/NutrientAnalysisModal.tsx
You break it, you buy it (Nutrient Analysis table bugs fixed)
---
- [Frontend](https://nr-nmp-340.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-340-backend.apps.silver.devops.gov.bc.ca/healthcheck/)
> fix: Nutrient Analysis name mismatch

- frontend/src/calculations/FieldAndSoil/Crops/Calculations.ts
- frontend/src/common.styles.ts
- frontend/src/constants/DefaultNMPFileCropsData.ts
- frontend/src/constants/harvestUnits.ts
- frontend/src/constants/index.ts
- frontend/src/types/Crops.ts
- frontend/src/types/NMPFileFieldData.ts
- frontend/src/types/index.ts
- frontend/src/views/CalculateNutrients/CalculateNutrientsComponents/OtherModal.tsx
- frontend/src/views/Crops/CropsModal.tsx
- Corrected spelling error in "protein"
- Changed cropId typing to number (it was already a number but was being typed as a string)
- Added Harvest Unit dropdown (values from table, added as constant instead of table)
- Added yield harvest unit to crop (IMPORTANT NOTE: I did not yet alter calculations with this new information. Will do that in my next ticket fixing crop calculation numbers)
- Nicer formatting for TextFields
- Added modal handling of Other crop type
- Switched to using database values for multiple crop type properties (in case Josh makes weird changes and expects them to work)
- Reorganized Crops modal logic to match old NMP
- Reset crop id when crop type id changes
---
Deployments, as required, will be …
> fix: Fixing multiple crop modal bugs

- frontend/src/views/CalculateNutrients/CalculateNutrients.tsx
- frontend/src/views/CalculateNutrients/utils.tsx
Update Calculate Nutrients page by aligning column headers of multiple tables
---
- [Frontend](https://nr-nmp-384.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-384-backend.apps.silver.devops.gov.bc.ca/healthcheck/)
> feat: [NR-NMP-361] Realign CalcNutrients column headers, adjust table formatting

- frontend/package-lock.json
- frontend/package.json
- frontend/public/mockServiceWorker.js
- Updated eslint-config-prettier to latest
---
- [Frontend](https://nr-nmp-389.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-389-backend.apps.silver.devops.gov.bc.ca/healthcheck/)
> chore: Package upgrade for security

- frontend/src/types/Animals.ts
- frontend/src/types/Common.ts
- frontend/src/views/AddAnimals/AddAnimalsModal.tsx
- frontend/src/views/AddAnimals/AnimalFormComponents/OtherAnimals.tsx
- frontend/src/views/FarmInformation/FarmInformation.tsx
- Swine added as animal option
- Swine modal with manure type and swine subtype options
- Auto assign subtypes to other animals
- Manure calculations for solid and liquid
---
- [Frontend](https://nr-nmp-408.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-408-backend.apps.silver.devops.gov.bc.ca/healthcheck/)
> feat(NMP-117): Swine Modal

- frontend/src/components/common/NumberField/NumberField.css
- frontend/src/components/common/TextField/TextField.css
- frontend/src/constants/DefaultBerryData.ts
- frontend/src/constants/DefaultNMPFile.ts
- frontend/src/constants/DefaultNMPFileCropsData.ts
- frontend/src/constants/DefaultSoilTestData.ts
- frontend/src/constants/index.ts
- frontend/src/types/Crops.ts
- frontend/src/types/NMPFile.ts
- frontend/src/types/NMPFileFieldData.ts
- frontend/src/views/Crops/CropsModal.tsx
- frontend/src/views/Crops/utils.ts
- frontend/src/views/FarmInformation/FarmInformation.tsx
- frontend/src/views/Reporting/ReportTemplates/FieldDetailSection.tsx
- frontend/src/views/Reporting/reporting.styles.ts
- Leaf tests added to berries option in crops modal
- Leaf and soil tests passed into calcs (user data or default values)
- Adjusted report styling for better readability
- Small linting errors fixed
- Leaf tests added to report (Not sure how it should look, as it doesn't appear in old NMP
Leaf test in crops modal for berries: 
Leaf tests in report:
---
- [Frontend](https://nr-nmp-414.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-414-backend.apps.silver.devops.gov.bc.ca/healthcheck/)
After merge, new images are …
> feat: [NR-NMP-284] Leaf Tests

- frontend/src/calculations/ManureAndCompost/ManureAndImports/Calculations.ts
- Update calculations.ts for nitrogen removal to properly account for application rate 
---
- [Frontend](https://nr-nmp-478.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-nmp-478-backend.apps.silver.devops.gov.bc.ca/healthcheck/)
> fix: [NR-NMP-453] Update calculation formula for nitrogen removal
